<?php

namespace BetaOmega\AppBundle\Repository;

/**
 * ComplaintsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get complaint on question
     */
    public function getComplaintQuestion()
    {
        $qb = $this->createQueryBuilder('q')
            ->select('q')
            ->where('q.question IS NOT NULL');

        return $qb->getQuery()->getResult();
    }

    /**
     * Get complaint on tpics
     */
    public function getComplaintTopic()
    {
        $qb = $this->createQueryBuilder('q')
            ->select('q')
            ->where('q.topic IS NOT NULL');

        return $qb->getQuery()->getResult();
    }

    /**
     * Get complaint on reviews
     */
    public function getComplaintReview()
    {
        $qb = $this->createQueryBuilder('q')
            ->select('q')
            ->where('q.review IS NOT NULL');

        return $qb->getQuery()->getResult();
    }
}
