<?php

namespace BetaOmega\AppBundle\Repository;

/**
 * YearOfStudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearOfStudyRepository extends \Doctrine\ORM\EntityRepository
{
}
