parameters:
    ccy: ccy
    download: the-most-download
    commented: the-most-commented
    recomended: recomended

services:
    beta-omega.search.service:
        class: BetaOmega\SearchBundle\Services\SearchService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@service_container"]
        calls:
            - [setRequest, ["@request_stack"]]
